#Requires -Version 5.1
$ErrorActionPreference = 'Stop'

# PostToolUse hook: fires on every Edit/Write.
# Self-filters: exits immediately unless the edited file is .claude/workspace.yaml.

$raw = [Console]::In.ReadToEnd()
if (-not $raw) { exit 0 }

try { $payload = $raw | ConvertFrom-Json } catch { exit 0 }

$editedFile = $payload.tool_input.file_path
if (-not $editedFile) { exit 0 }

$normalized = $editedFile -replace '\\', '/'
if ($normalized -notlike '*/.claude/workspace.yaml') { exit 0 }

# ── Locate repo root (.claude/hooks/ → .claude/ → repo root) ──────────────
$repoRoot = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$yamlPath = Join-Path $repoRoot ".claude\workspace.yaml"

if (-not (Test-Path $yamlPath)) {
    Write-Error "workspace.yaml not found at $yamlPath"
    exit 1
}

# ── Parse workspace.yaml (hand-parser, no external deps) ──────────────────
$entries      = [System.Collections.Generic.List[hashtable]]::new()
$defaultOwner = '@raonrabbit'
$currentEntry = $null
$inMeta       = $false
$inSection    = $false   # true when inside packages: or apps:

foreach ($line in (Get-Content $yamlPath)) {
    if ($line -match '^\s*#')           { continue }
    if ($line -match '^meta:')          { $inMeta = $true; $inSection = $false; continue }
    if ($line -match '^packages:')      { $inMeta = $false; $inSection = $true;  continue }
    if ($line -match '^apps:')          { $inMeta = $false; $inSection = $true;  continue }

    if ($inMeta -and $line -match '^\s+default_owner:\s*"?([^"#\r\n]+?)"?\s*$') {
        $defaultOwner = $Matches[1].Trim()
    }

    if ($inSection) {
        if ($line -match '^\s+-\s+path:\s+(.+)') {
            if ($currentEntry) { $entries.Add($currentEntry) }
            $currentEntry = @{ path = $Matches[1].Trim(); scope = ''; owner = $defaultOwner }
        }
        elseif ($currentEntry -and $line -match '^\s+scope:\s*"?([^"#\r\n]+?)"?\s*$') {
            $currentEntry.scope = $Matches[1].Trim()
        }
        elseif ($currentEntry -and $line -match '^\s+owner:\s*"?([^"#\r\n]+?)"?\s*$') {
            $currentEntry.owner = $Matches[1].Trim()
        }
    }
}
if ($currentEntry) { $entries.Add($currentEntry) }

if ($entries.Count -eq 0) {
    Write-Error "workspace.yaml parsed 0 entries. Check YAML syntax."
    exit 1
}

foreach ($e in $entries) {
    if (-not $e.path -or -not $e.scope -or -not $e.owner) {
        Write-Error "Entry missing required field (path/scope/owner): $($e | ConvertTo-Json -Compress)"
        exit 1
    }
}

# ── Generate .github/CODEOWNERS ───────────────────────────────────────────
$githubDir = Join-Path $repoRoot ".github"
if (-not (Test-Path $githubDir)) { New-Item -ItemType Directory -Path $githubDir | Out-Null }

$codeownersPath = Join-Path $githubDir "CODEOWNERS"
$coLines = @(
    "# AUTO-GENERATED by .claude/hooks/sync-workspace.ps1",
    "# Source of truth: .claude/workspace.yaml",
    "# DO NOT edit this file directly.",
    ""
)
foreach ($e in $entries) {
    $coLines += "/$($e.path)/`t$($e.owner)"
}
[System.IO.File]::WriteAllText($codeownersPath, ($coLines -join "`n") + "`n", [System.Text.Encoding]::UTF8)

# ── Patch ship/SKILL.md scopes (sentinel-bounded replacement) ─────────────
$skillPath = Join-Path $repoRoot ".claude\skills\ship\SKILL.md"
if (-not (Test-Path $skillPath)) {
    Write-Warning "ship/SKILL.md not found — skipping scope sync."
} else {
    $skillContent = [System.IO.File]::ReadAllText($skillPath, [System.Text.Encoding]::UTF8)

    $startSentinel = "<!-- workspace-scopes:start -->"
    $endSentinel   = "<!-- workspace-scopes:end -->"

    if ($skillContent -notlike "*$startSentinel*") {
        Write-Warning "ship/SKILL.md is missing workspace-scopes sentinels — skipping scope sync."
    } else {
        $rows = foreach ($e in $entries) { "| ``$($e.scope)`` | ``$($e.path)/`` |" }
        $block = $startSentinel + "`n" + ($rows -join "`n") + "`n" + $endSentinel

        $pattern    = [regex]::Escape($startSentinel) + "[\s\S]*?" + [regex]::Escape($endSentinel)
        $newContent = [regex]::Replace($skillContent, $pattern, $block)

        [System.IO.File]::WriteAllText($skillPath, $newContent, [System.Text.Encoding]::UTF8)
    }
}

exit 0
