pkg:ui:
    - changed-files:
          - any-glob-to-any-file: "packages/ui/**"

pkg:figma-plugin:
    - changed-files:
          - any-glob-to-any-file: "packages/figma-plugin/**"

app:dev-news:
    - changed-files:
          - any-glob-to-any-file: "apps/dev-news/**"

app:mercari-kor:
    - changed-files:
          - any-glob-to-any-file: "apps/mercari-kor/**"

app:my-page:
    - changed-files:
          - any-glob-to-any-file: "apps/my-page/**"

infra:
    - changed-files:
          - any-glob-to-any-file:
                - ".github/**"
                - "turbo.json"
                - "pnpm-workspace.yaml"
                - "package.json"
                - "pnpm-lock.yaml"
